// <auto-generated />
using System;
using HessTrucks.Services.TruckCatalog.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HessTrucks.Services.TruckCatalog.Migrations
{
    [DbContext(typeof(TruckCatalogDbContext))]
    [Migration("20210111200137_1ToManyTruckCategory")]
    partial class _1ToManyTruckCategory
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("HessTrucks.Services.TruckCatalog.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("HessTrucks.Services.TruckCatalog.Entities.Photo", b =>
                {
                    b.Property<Guid>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TruckId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PhotoId");

                    b.HasIndex("TruckId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("HessTrucks.Services.TruckCatalog.Entities.Truck", b =>
                {
                    b.Property<Guid>("TruckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Damaged")
                        .HasColumnType("bit");

                    b.Property<string>("DefaultPhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Hidden")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PreviousPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("TruckId");

                    b.ToTable("Trucks");
                });

            modelBuilder.Entity("HessTrucks.Services.TruckCatalog.Entities.TruckCategory", b =>
                {
                    b.Property<Guid>("TruckId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("TruckId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("TruckCategory");
                });

            modelBuilder.Entity("HessTrucks.Services.TruckCatalog.Entities.Photo", b =>
                {
                    b.HasOne("HessTrucks.Services.TruckCatalog.Entities.Truck", "Truck")
                        .WithMany("Photos")
                        .HasForeignKey("TruckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Truck");
                });

            modelBuilder.Entity("HessTrucks.Services.TruckCatalog.Entities.TruckCategory", b =>
                {
                    b.HasOne("HessTrucks.Services.TruckCatalog.Entities.Category", "Category")
                        .WithMany("TruckCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HessTrucks.Services.TruckCatalog.Entities.Truck", "Truck")
                        .WithMany("TruckCategories")
                        .HasForeignKey("TruckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Truck");
                });

            modelBuilder.Entity("HessTrucks.Services.TruckCatalog.Entities.Category", b =>
                {
                    b.Navigation("TruckCategories");
                });

            modelBuilder.Entity("HessTrucks.Services.TruckCatalog.Entities.Truck", b =>
                {
                    b.Navigation("Photos");

                    b.Navigation("TruckCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
